apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/name: pilot
    app.kubernetes.io/managed-by: kustomize
  name: kompass-rightsizing-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kompass-rightsizing-manager-role
subjects:
- kind: ServiceAccount
  name: {{ include "pod-rightsizing.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/name: pilot
    app.kubernetes.io/managed-by: kustomize
  name: kompass-rightsizing-cm-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kompass-rightsizing-cm-manager-role
subjects:
- kind: ServiceAccount
  name: {{ include "pod-rightsizing.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
